ghooks-org/ghooks

lib/install.js
package.json

This pull request updates the install action in the package.json and the project root search in the install script so that it's more friendly with Windows.
Tested on OS X Yosemite and WIndows 7.

Add Windows support to install

---

lib/install.js

Maybe I have missed something here but I think the projectRoot should be set to the parent project folder. The problem we have is that we have a sub lib to our main app that is dependent on ghooks. When we run npm install from our main project ghooks installs the hooks in that project causing it to fail during commits due to the fact that ghooks is not installed in that project. Do you get it =)
And the way projectRoot now is set this is by design.

Settings projectRoot to parent projects folder

---

README.md

I was just setting this up in my repo and `$1` was causing problems with `validate-commit-msg`. It would always fail and then add `#!/usr/bin/env node` to the *end* of `.git/hooks/commit-msg` making the hook unable to run from that point on.
I tested a positive and negative case without `$1`. It allows the commit with a valid message and disallows the commit with an invalid message.

Remove arg from `commit-msg` sample hook.

---

.jshintrc
lib/install.js
lib/runner.js
package.json
test/runner.test.js

Fixes #35, #28, #3. Closes #36
This uses the [findup] package to traverse up the directory tree of
the current working directory, to find `package.json`, or `.git`.
It does so to allow for edge-case situations, such as described in
and #35 (executing hooks from a different working dir, for example
with `git --work-tree`).
As part of this commit, the JSHint maxcomplexity/maxstatements
numbers have been bumped by 1.
[findup]: https://www.npmjs.com/package/findup
---
Note: I think #36 (/cc @gtramontina) should be closed as the functionality in this PR overlaps that of #36.

Use findup to traverse tree for .git, package.json

---

.travis.yml
package.json

@kentcdodds :wave: 
Semantic release is failing to publish to npm properly because matrix
builds inside travis cause a race condition in npm publish. travis
executes the npm publish step at the same time and therefore npm
screws up the publish.
This adds travis-after-all which prevents the sidecar builds from
publishing, and the main build waits until the sidecar builds have
passed before publishing.
I've implemented this before (see [this package.json](https://github.com/packagesmith/provision-npm-babel/blob/master/package.json#L59), [this travis.yml](https://github.com/packagesmith/provision-npm-babel/blob/master/.travis.yml#L11) and [this example build job](https://travis-ci.org/packagesmith/provision-npm-babel/jobs/100317363) if you want to see it in action).

chore(travis): fix matrix build errors

---

.gitignore
CONTRIBUTING.md
README.md
package.json

Do not merge yet...
This is to add @ta2edchimp's awesome new [opt-in](https://github.com/ta2edchimp/opt-cli) package.
There are, however a few issues with `opt-in` we need resolved before this can be merged. Will file them soon.
1. The output is not streamed to the stdout/err which means you see no output until it's done (if it ever finishes). The cli package that's being used evidently isn't setting `stdio: 'inherit'` as it should (like [this](https://github.com/gtramontina/ghooks/blob/5ac56bf5869cc1dd69db6dad83ae6cbcf1dac0aa/lib/runner.js#L34)).
2. I think that the command is not executed with the proper `$PATH` because I don't think that it can find `validate-commit-msg` which is in `node_modules/.bin/` which [we add](https://github.com/gtramontina/ghooks/blob/5ac56bf5869cc1dd69db6dad83 …

Add opt-in functionality

---

bin/install
lib/hook.template.raw
package.json

- Removed `babel-cli` as a dependency, as it became unnecessary with cb5187a.
- Completed the code adjustments (include `lib/hook.template.raw` into linting process).
To complement #43

Complete code style adjustion

---

package.json

The `install` script has been adjusted to invoke `npm run build` on `install` if the `dist` dir is not present (that is, when fetching from git or sth like that).
**Note for Windows**
I have no idea if this solution would suffice in Windows environments. I guess the script will fail due to the default command line (`cmd.exe`) not recognizing the statement. Any ideas?

Fix: Build package prior to installing

---

lib/hook.template.raw
test/hook.template.raw.test.js

- Adjusted test to take into account that the hooks' scripts now return with an error if ghooks couldn't be found.
- Adjusted original commit message to comply with conventions.

Follow up to #50: Exit with error if ghooks is not found

---

bin/install
package.json

Using node to check whether running `npm run build` is required.
Closes #63 
---
I was looking for something like `path-exists` but with a CLI. This way we could simply replace `[ ! -d \"./dist\" ] && …` with `pathExits "./dist" || …`. Then we could also get rid of `execa`.
*Maybe I'll submit `path-exists` a PR :thought_balloon:*

Build package prior to installing

---

.travis.yml

Uses npm 2.x on Node versions 0.10 and 0.12 on Travis.
Keeps using npm 3.x on Node versions 4 and 5.
Relates to #71 and the discussion within (starting [here](https://github.com/gtramontina/ghooks/issues/71#issuecomment-204148795)).

chore(ci): Build with multiple npm versions on Travis

---

lib/hook.template.raw
lib/install.js
package.json
test/hook.template.raw.test.js
test/install.test.js

At the moment, this PR is rather a proof and is more for the purpose to get feedback early on, as well as to keep track of the progress (and of the key ideas for me to remember when getting back on this after I had some sleep).
When finished, this PR will address the issue #46 and probably #66 too, as their key difference to a usual git repo is identical.
In current versions of git, submodules don't have a `.git` folder in their root directory (and therefore, no `.git/hooks` folder too). Instead, they have a config **file** called `.git`, with something like the following content:
```
gitdir: ../.git/modules/submod-1
```
So this is basically the pointer towards where the submodule's `hooks` directory will reside. Accordingly, I altered ghooks' `./lib/install.js` to take this into account. …

Support submodules & worktrees

---

lib/hook.template.raw
test/hook.template.raw.test.js

By default, do not exit with an error if ghooks is not found.
This is to a) fix #70 and b) the preparation to introduce that behavior as optional.

fix: Don't exit with non-zero code on error

---

lib/install.js

docs(install): instruct to use npm explore in non-git repo warning

---

bin/module-install
package.json

This should tackle #71 
What it does:
* Extracts the former npm `install` script into a separate one within `./bin` and calls **that** on `install`.
* Tries to use `opt-cli` as a library rather than as a cli tool and only invokes `ghooks` very own `./bin/install`, when `opt-cli` was found **and** the user has not opted-out of `ghooks-install`.
* Prints out the following warning if ghooks could not auto-run its installation script on `npm install`:
```
ghooks postinstall could not be completed.
==========================================
Usually this is due to using npm@2.15.x. Please consider updating npm
to its latest version or run the following command manually afterwards:
node ./bin/install
```
An alternative to this could be to just run the install script and warn that a possible …

Fail gracefully on occasional npm@2.15 hickups

---

.npmignore
README.md
appveyor.yml
test/.eslintrc
test/hook.template.raw.test.js
test/runner.test.js
test/setup.js

As suggested by @ta2edchimp on https://github.com/gtramontina/ghooks/pull/114#issuecomment-230234358
---
Interestingly enough, a few tests fail running on windows. Three of them are `/` vs. `\` on assertions… (classic! 😛) The fourth and last one is related to setting the PATH… ~~I'll look into those tomorrow.~~ 
The last [failed test](https://github.com/gtramontina/ghooks/blob/4bc83c0577cb6cc1ce6319f3030307c748106d89/test/runner.test.js#L53-L59) still persists. I'll need a bit more time to investigate as maybe I'll require a VM do help out (or, in the meanwhile, someone could 👀 spot what the issue might be 😉).
I've also made `continuous-integration/travis-ci/pr` required for PRs to be merged. And as soon as this one gets in (I'm planning on fixing the tests on this same PR), I'll make …

Setup Appveyor

---

README.md

Hi @gtramontina,
To simplify transition for bigger projects, I've updated husky to automatically migrate hooks that contain `// Generated by ghooks...`.
Migrating should now just be a matter of uninstalling ghooks and installing husky, here's an example:
```sh
$ npm install ghooks --save-dev && npm uninstall ghooks --save-dev
$ npm install husky --save-dev 
> husky@0.13.1 install /tmp/test/node_modules/husky
> node ./bin/install.js
husky
setting up hooks
migrating ghooks applypatch-msg script
migrating ghooks pre-applypatch script
...
```
Hope it will help :)

docs(readme): update note about migrating to husky

---

README.md

This is so we get the badges working again (have to re-enable them for the new repository path).

docs(readme): replace gtramontina with ghooks-org

---

.gitignore
lib/hook.template.raw
test/hook.template.raw.test.js

Hooks break when the path changes, this is terrible functionality. So
let's use the relative path like the rest of the system and be happy. We
will fallback to the old behavior just for fun.

Relative Path

---

lib/hook.template.raw
test/hook.template.raw.test.js

According to the docs (https://nodejs.org/api/path.html) `path.resolve` only ever throws for type errors (if any of the arguments aren't a string), not if the path does not exist. For that we have to use `fs.stat`/`fs.statSync`.

fix: node_modules absolute entry point never getting found
